Scix 170 author network graph using d 3
adsabs/nectar pull request #233
Opened 2022-07-28 13:52 UTC by shinyichen

depends on #231 

# Updated D3 graph for author network
* Replaced sunburst graph with `visualizations/Graphs/NetworkGraph`
* `visualizations/Graphs/useNetworkGraph` creates the d3 functions to calculate the graph elements for rendering

<img width="620" alt="Screen Shot 2022-07-27 at 6 36 32 PM" src="https://user-images.githubusercontent.com/636361/181384345-191a6f79-75d9-44a4-8f76-491ac10466a8.png">
<img width="593" alt="Screen Shot 2022-07-27 at 6 37 16 PM" src="https://user-images.githubusercontent.com/636361/181384435-b6088402-1772-4f10-8d0c-f028fe443d3e.png">

2022-08-03 08:19 UTC, thostetler requested changes
Good job on this, I know it was a ton of work 👍 

I have a few things I think we should work on. 

- For the main container, we can pull out the logic into a reducer to help separate that state management, since really it's the top-level component that passes props around.

- In a few areas there are some mutating logic that I think in general we should try to avoid since it can introduce bugs, but probably fine for these helper functions, since the values are ephemeral.

-  Playing with the author network itself, I noticed that there is a long lag after changing between views (author occurences, paper citations, paper downloads).  Not just a lag though, it's blocking on the main thread, so this one needs to be fixed.

- There is quite a bit of prop drilling that is happening.  I think you could move some of this into it's own store slice in the global store.  I'm not sure how much unnecessary rendering is happening though, just an observation!

Overall I think this looks pretty good and works well! I would be happy to help with any changes you decide you want to make.  

We can also discuss merging and then doing a refactor since there are a bunch of other things added/changed in here beyond the author network.

2022-08-03 15:18 UTC, shinyichen commented on src/components/Expandable/Expandable.tsx
> +  const [isOpen, setIsOpen] = useState(false);
Updated

2022-08-03 15:18 UTC, shinyichen commented on src/components/Tags/Tags.tsx
> +            <TagCloseButton onClick={() => handleRemoveItem(item)} />
Updated

2022-08-03 15:18 UTC, shinyichen commented on src/components/Visualizations/Containers/AuthorNetworkPageContainer.tsx
> +    }
Updated

2022-08-03 15:19 UTC, shinyichen commented on src/components/Visualizations/GraphPanes/NetworkGraphPane.tsx
> +  onChagePaperLimit: (limit: number) => void;
Fixed

2022-08-03 15:19 UTC, shinyichen commented on src/components/Visualizations/Graphs/NetworkGraph.tsx
> +  const transitionLinks = useCallback((links: ILink[]) => {
Removed

2022-08-04 19:59 UTC, merged

2022-08-08 18:24 UTC, shinyichen commented
@thostetler I'd like to get your opinion on this topic:
> * There is quite a bit of prop drilling that is happening.  I think you could move some of this into it's own store slice in the global store.  I'm not sure how much unnecessary rendering is happening though, just an observation!

Looking at my code, here are where the prop drillings happen:
1) Main container -> network graph pane -> network graph
    The data passed down are the parts of the response used for the graph and limit. I definitely don't want the base component (network graph) to have any knowledge of where this data comes from, it should just use whatever parent passes so it is reusable. 
2) Main container -> network details
    Passing the summary graph and selected node

Based on that, I don't feel too much of prop drilling here.  Do you still recommend moving some of the data into store?

2022-08-08 19:13 UTC, thostetler commented
Yeah you're right it's not a lot.  I think my main concern is that any changes to that root state is going to re-render several large components possibly unnecessarily.
If you don't notice any real extra re-rendering then we can leave it for now. 
I would recommend though rather than passing down lots of handlers/state.  Make a reducer and pass the piece of state you need and the dispatch function to the children.  Then you can do whatever updates without the need for the extra handlers

2022-08-08 19:28 UTC, shinyichen commented
I've updated the code with the reducer (will be in a different PR). And I wonder if the main thread blocking issue was from my old graph code, not the D3 code. I did have problem with the old graph switching view, but with D3 there should be no lag.

2022-08-08 19:31 UTC, shinyichen commented
https://user-images.githubusercontent.com/636361/183499008-b8ce24f3-fa5e-43d3-b9a6-002faeddafa2.mov